<?php
declare(strict_types=1);

namespace App\Traits;

trait CurrencyTrait
{
    public function formatAmount(
        float|string $amount,
        string $currency = null,
        bool $appendSymbol = true,
        int $decimals = 2,
        string $decimalSeparator = '.',
        string $thousandsSeparator = ','
    ): string {
        // Convert amount to float
        $amount = (float) $amount;
    
        // Example: Retrieve settings from a config or a service
        $setting = [
            'currency' => 'USD',
            'currency_symbol' => '$',
            'decimal_digit' => 2,
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency_position' => 'left',
        ];
    
        // Fallback for currency and symbol if not set
        $currency = $currency ?? $setting['currency'] ?? 'USD';
        $symbol = $setting['currency_symbol'] ?? '$';
        $decimals = $setting['decimal_digit'] ?? $decimals;
        $decimalSeparator = $setting['decimal_separator'] ?? $decimalSeparator;
        $thousandsSeparator = $setting['thousands_separator'] ?? $thousandsSeparator;
    
        // Format the amount
        $formattedAmount = number_format(
            $amount,
            $decimals,
            $decimalSeparator,
            $thousandsSeparator
        );
    
        // Determine whether to append the symbol or currency code
        $appendCharacter = $appendSymbol ? $symbol : strtoupper($currency);
    
        // Determine currency position (left or right)
        $currencyPosition = $setting['currency_position'] ?? 'left';
    
        // Append the currency symbol or code based on position
        if ($currencyPosition === 'left') {
            $formattedAmount = "{$appendCharacter}{$formattedAmount}";
        } else {
            $formattedAmount = "{$formattedAmount}{$appendCharacter}";
        }
    
        return $formattedAmount;
    }
    

    public function getCurrenciesByCountries(): array
    {
        return [
            'AF' => 'AFN',
            'AL' => 'ALL',
            'DZ' => 'DZD',
            'AS' => 'USD',
            'AD' => 'EUR',
            'AO' => 'AOA',
            'AI' => 'XCD',
            'AQ' => 'USD',
            'AG' => 'XCD',
            'AR' => 'ARS',
            'AM' => 'AMD',
            'AW' => 'AWG',
            'AU' => 'AUD',
            'AT' => 'EUR',
            'AZ' => 'AZN',
            'BS' => 'BSD',
            'BH' => 'BHD',
            'BD' => 'BDT',
            'BB' => 'BBD',
            'BY' => 'BYN',
            'BE' => 'EUR',
            'BZ' => 'BZD',
            'BJ' => 'XOF',
            'BM' => 'BMD',
            'BT' => 'BTN',
            'BO' => 'BOB',
            'BQ' => 'USD',
            'BA' => 'BAM',
            'BW' => 'BWP',
            'BV' => 'NOK',
            'BR' => 'BRL',
            'IO' => 'USD',
            'BN' => 'BND',
            'BG' => 'BGN',
            'BF' => 'XOF',
            'BI' => 'BIF',
            'CV' => 'CVE',
            'KH' => 'KHR',
            'CM' => 'XAF',
            'CA' => 'CAD',
            'KY' => 'KYD',
            'CF' => 'XAF',
            'TD' => 'XAF',
            'CL' => 'CLP',
            'CN' => 'CNY',
            'CX' => 'AUD',
            'CC' => 'AUD',
            'CO' => 'COP',
            'KM' => 'KMF',
            'CG' => 'XAF',
            'CD' => 'CDF',
            'CK' => 'NZD',
            'CR' => 'CRC',
            'HR' => 'HRK',
            'CU' => 'CUP',
            'CW' => 'ANG',
            'CY' => 'EUR',
            'CZ' => 'CZK',
            'CI' => 'XOF',
            'DK' => 'DKK',
            'DJ' => 'DJF',
            'DM' => 'XCD',
            'DO' => 'DOP',
            'EC' => 'USD',
            'EG' => 'EGP',
            'SV' => 'USD',
            'GQ' => 'XAF',
            'ER' => 'ERN',
            'EE' => 'EUR',
            'SZ' => 'SZL',
            'ET' => 'ETB',
            'FK' => 'FKP',
            'FO' => 'DKK',
            'FJ' => 'FJD',
            'FI' => 'EUR',
            'FR' => 'EUR',
            'GF' => 'EUR',
            'PF' => 'XPF',
            'GA' => 'XAF',
            'GM' => 'GMD',
            'GE' => 'GEL',
            'DE' => 'EUR',
            'GH' => 'GHS',
            'GI' => 'GIP',
            'GR' => 'EUR',
            'GL' => 'DKK',
            'GD' => 'XCD',
            'GP' => 'EUR',
            'GU' => 'USD',
            'GT' => 'GTQ',
            'GG' => 'GBP',
            'GN' => 'GNF',
            'GW' => 'XOF',
            'GY' => 'GYD',
            'HT' => 'HTG',
            'HN' => 'HNL',
            'HK' => 'HKD',
            'HU' => 'HUF',
            'IS' => 'ISK',
            'IN' => 'INR',
            'ID' => 'IDR',
            'IR' => 'IRR',
            'IQ' => 'IQD',
            'IE' => 'EUR',
            'IM' => 'GBP',
            'IL' => 'ILS',
            'IT' => 'EUR',
            'JM' => 'JMD',
            'JP' => 'JPY',
            'JE' => 'GBP',
            'JO' => 'JOD',
            'KZ' => 'KZT',
            'KE' => 'KES',
            'KI' => 'AUD',
            'KP' => 'KPW',
            'KR' => 'KRW',
            'KW' => 'KWD',
            'KG' => 'KGS',
            'LA' => 'LAK',
            'LV' => 'EUR',
            'LB' => 'LBP',
            'LS' => 'LSL',
            'LR' => 'LRD',
            'LY' => 'LYD',
            'LI' => 'CHF',
            'LT' => 'EUR',
            'LU' => 'EUR',
            'MO' => 'MOP',
            'MK' => 'MKD',
            'MG' => 'MGA',
            'MW' => 'MWK',
            'MY' => 'MYR',
            'MV' => 'MVR',
            'ML' => 'XOF',
            'MT' => 'EUR',
            'MH' => 'USD',
            'MQ' => 'EUR',
            'MR' => 'MRU',
            'MU' => 'MUR',
            'YT' => 'EUR',
            'MX' => 'MXN',
            'FM' => 'USD',
            'MD' => 'MDL',
            'MC' => 'EUR',
            'MN' => 'MNT',
            'ME' => 'EUR',
            'MS' => 'XCD',
            'MA' => 'MAD',
            'MZ' => 'MZN',
            'MM' => 'MMK',
            'NA' => 'NAD',
            'NR' => 'AUD',
            'NP' => 'NPR',
            'NL' => 'EUR',
            'NC' => 'XPF',
            'NZ' => 'NZD',
            'NI' => 'NIO',
            'NE' => 'XOF',
            'NG' => 'NGN',
            'NU' => 'NZD',
            'NF' => 'AUD',
            'MP' => 'USD',
            'NO' => 'NOK',
            'OM' => 'OMR',
            'PK' => 'PKR',
            'PW' => 'USD',
            'PS' => 'ILS',
            'PA' => 'PAB',
            'PG' => 'PGK',
            'PY' => 'PYG',
            'PE' => 'PEN',
            'PH' => 'PHP',
            'PN' => 'NZD',
            'PL' => 'PLN',
            'PT' => 'EUR',
            'PR' => 'USD',
            'QA' => 'QAR',
            'RE' => 'EUR',
            'RO' => 'RON',
            'RU' => 'RUB',
            'RW' => 'RWF',
            'BL' => 'EUR',
            'SH' => 'SHP',
            'KN' => 'XCD',
            'LC' => 'XCD',
            'MF' => 'EUR',
            'PM' => 'EUR',
            'VC' => 'XCD',
            'WS' => 'WST',
            'SM' => 'EUR',
            'ST' => 'STN',
            'SA' => 'SAR',
            'SN' => 'XOF',
            'RS' => 'RSD',
            'SC' => 'SCR',
            'SL' => 'SLL',
            'SG' => 'SGD',
            'SX' => 'ANG',
            'SK' => 'EUR',
            'SI' => 'EUR',
            'SB' => 'SBD',
            'SO' => 'SOS',
            'ZA' => 'ZAR',
            'GS' => 'GBP',
            'SS' => 'SSP',
            'ES' => 'EUR',
            'LK' => 'LKR',
            'SD' => 'SDG',
            'SR' => 'SRD',
            'SJ' => 'NOK',
            'SE' => 'SEK',
            'CH' => 'CHF',
            'SY' => 'SYP',
            'TW' => 'TWD',
            'TJ' => 'TJS',
            'TZ' => 'TZS',
            'TH' => 'THB',
            'TL' => 'USD',
            'TG' => 'XOF',
            'TK' => 'NZD',
            'TO' => 'TOP',
            'TT' => 'TTD',
            'TN' => 'TND',
            'TR' => 'TRY',
            'TM' => 'TMT',
            'TC' => 'USD',
            'TV' => 'AUD',
            'UG' => 'UGX',
            'UA' => 'UAH',
            'AE' => 'AED',
            'GB' => 'GBP',
            'US' => 'USD',
            'UM' => 'USD',
            'UY' => 'UYU',
            'UZ' => 'UZS',
            'VU' => 'VUV',
            'VE' => 'VES',
            'VN' => 'VND',
            'VG' => 'USD',
            'VI' => 'USD',
            'WF' => 'XPF',
            'EH' => 'MAD',
            'YE' => 'YER',
            'ZM' => 'ZMW',
            'ZW' => 'ZWL',
        ];
    }


    public function getCurrencyByCountryCode(string $countryCode): string
    {
        $countryCode = strtoupper($countryCode);
        $currencies = $this->getCurrenciesByCountries();
        return $currencies[$countryCode] ?? 'USD';
    }

}
